---
title: "P03 Calculate z-score for each data set and combine"
author: "Joss Ives"
date: "June 10, 2018"
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*updated by Joss Ives `r format(Sys.time(), "%Y %B %d, %H:%M:%S")`*

# Setup

```{r echo=FALSE}
# Load libraries
library(plyr)
#library(PerformanceAnalytics)
library(dplyr)
```

# P100 MT

```{r echo=FALSE}
# Load data
derived0.P100MT <- read.csv("C:/Users/Joss/ownCloud/Shared/DP_Derived_Data/dpLogisticDat_P100MT.csv")
names(derived0.P100MT)
```
### Add additional calculated values
```{r echo=FALSE}
dat<-derived0.P100MT
totalpts = 36.
dat$tempGrade <- dat$SoloTotal36.M0
dat <- select(dat, -SoloTotal36.M0)
#
dat$ExamGrade.100 <- dat$tempGrade/totalpts*100.
dat$ExamGrade.fix <- (dat$tempGrade-2.*dat$QCORRECT)/(totalpts-2.)
dat$ExamGrade.LMH <- as.integer(
  cut(dat$tempGrade, quantile(dat$tempGrade, probs=0:3/3), include.lowest=TRUE)
  )
exam.mean = mean(dat$ExamGrade.fix)
exam.sd = sd(dat$ExamGrade.fix)
dat$ExamGrade.fix.z <- (dat$ExamGrade.fix-exam.mean)/exam.sd

derived1.P100MT <- select(dat, -tempGrade)
names(derived1.P100MT)
```

# P100 Final 

```{r echo=FALSE}
derived0.P100F <- read.csv("C:/Users/Joss/ownCloud/Shared/DP_Derived_Data/dpLogisticDat_P100F.csv")
names(derived0.P100F)
```

### Add additional calculated values

```{r echo=FALSE}
dat<-derived0.P100F
totalpts = 74.
dat$tempGrade <- dat$SoloTotal74.F0
dat <- select(dat, -SoloTotal74.F0)
#
dat$ExamGrade.100 <- dat$tempGrade/totalpts*100.
dat$ExamGrade.fix <- (dat$tempGrade-2.*dat$QCORRECT)/(totalpts-2.)
dat$ExamGrade.LMH <- as.integer(
  cut(dat$tempGrade, quantile(dat$tempGrade, probs=0:3/3), include.lowest=TRUE)
  )
exam.mean = mean(dat$ExamGrade.fix)
exam.sd = sd(dat$ExamGrade.fix)
dat$ExamGrade.fix.z <- (dat$ExamGrade.fix-exam.mean)/exam.sd

derived1.P100F <- select(dat, -tempGrade)
names(derived1.P100F)
```

# P101 MT 

```{r echo=FALSE}
derived0.P101MT <- read.csv("C:/Users/Joss/ownCloud/Shared/DP_Derived_Data/dpLogisticDat_P101MT.csv")
names(derived0.P101MT)
```

### Add additional calculated values

```{r echo=FALSE}
dat<-derived0.P101MT
totalpts = 43.
dat$tempGrade <- dat$SoloTotal43.M1
dat <- select(dat, -SoloTotal43.M1)
#
dat$ExamGrade.100 <- dat$tempGrade/totalpts*100.
dat$ExamGrade.fix <- (dat$tempGrade-2.*dat$QCORRECT)/(totalpts-2.)
dat$ExamGrade.LMH <- as.integer(
  cut(dat$tempGrade, quantile(dat$tempGrade, probs=0:3/3), include.lowest=TRUE)
  )
exam.mean = mean(dat$ExamGrade.fix)
exam.sd = sd(dat$ExamGrade.fix)
dat$ExamGrade.fix.z <- (dat$ExamGrade.fix-exam.mean)/exam.sd

derived1.P101MT <- select(dat, -tempGrade)
names(derived1.P101MT)
```

# P101 Final 

```{r echo=FALSE}
derived0.P101F <- read.csv("C:/Users/Joss/ownCloud/Shared/DP_Derived_Data/dpLogisticDat_P101F.csv")
names(derived0.P101F)
```

### Add additional calculated values

```{r echo=FALSE}
dat<-derived0.P101F
totalpts = 78.
dat$tempGrade <- dat$SoloTotal78.F1
dat <- select(dat, -SoloTotal78.F1)
#
dat$ExamGrade.100 <- dat$tempGrade/totalpts*100.
dat$ExamGrade.fix <- (dat$tempGrade-2.*dat$QCORRECT)/(totalpts-2.)
dat$ExamGrade.LMH <- as.integer(
  cut(dat$tempGrade, quantile(dat$tempGrade, probs=0:3/3), include.lowest=TRUE)
  )
exam.mean = mean(dat$ExamGrade.fix)
exam.sd = sd(dat$ExamGrade.fix)
dat$ExamGrade.fix.z <- (dat$ExamGrade.fix-exam.mean)/exam.sd

derived1.P101F <- select(dat, -tempGrade)
names(derived1.P101F)
```

# Try to make a combined data set

```{r}
derived1.all <- rbind(derived1.P100MT, derived1.P100F)
derived1.all <- rbind(derived1.all, derived1.P101MT)
derived1.all <- rbind(derived1.all, derived1.P101F)
#summary(derived1.all)
```

### Save file to anonymized folder

```{r}

dpOut <- "C:/Users/Joss/ownCloud/Shared/DP_Derived_Data/dpLogisticDat_all.csv"
write.csv(derived1.all, dpOut, row.names = FALSE)
```

